openapi: 3.1.0
x-stoplight:
  id: pj7ni7mkxl429
info:
  title: vcbnvc
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/users/{userId}':
    parameters:
      - schema:
          type: string
        name: userId
        in: path
        required: true
      - schema:
          type: string
        name: userId
        in: path
        required: true
      - schema:
          type: integer
        name: userId
        in: path
        required: true
        description: Id of an existing user.
    get:
      summary: Get User Info by User ID
      tags: []
      responses:
        '200':
          description: User Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                Get User Alice Smith:
                  value:
                    id: 142
                    firstName: Alice
                    lastName: Smith
                    email: alice.smith@gmail.com
                    dateOfBirth: '1997-10-31'
                    emailVerified: true
                    signUpDate: '2019-08-24'
        '404':
          description: User Not Found
      operationId: get-users-userId
      description: Retrieve the information of the user with the matching user ID.
      x-stoplight:
        id: fznvtnidc8n8k
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                esdfg:
                  $ref: 'https://integration.stoplight-dev.com/api/v1/projects/newint/newestdl/nodes/models/mjhhjgf.yaml?mid=5167'
                  x-stoplight:
                    id: 0cq8yoxu4l2m1
                hgbv:
                  $ref: 'https://integration.stoplight-dev.com/api/v1/projects/newint/git-3fdse3/nodes/reference/jhvukh.yaml/components/schemas/User?mid=4813'
                  x-stoplight:
                    id: thkw5lr068435
                cvbn:
                  type: string
                  x-stoplight:
                    id: eahwhhp7ag199
    patch:
      summary: Update User Information
      operationId: patch-users-userId
      responses:
        '200':
          description: User Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                Updated User Rebecca Baker:
                  value:
                    id: 13
                    firstName: Rebecca
                    lastName: Baker
                    email: rebecca@gmail.com
                    dateOfBirth: '1985-10-02'
                    emailVerified: false
                    createDate: '2019-08-24'
        '404':
          description: User Not Found
        '409':
          description: Email Already Taken
      description: Update the information of an existing user.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                  description: 'If a new email is given, the user''s email verified property will be set to false.'
                dateOfBirth:
                  type: string
            examples:
              Update First Name:
                value:
                  firstName: Rebecca
              Update Email:
                value:
                  email: rebecca@gmail.com
              Update Last Name & Date of Birth:
                value:
                  lastName: Baker
                  dateOfBirth: '1985-10-02'
        description: Patch user properties to update.
      x-stoplight:
        id: dxjluxilyuwgq
    post:
      summary: Your POST endpoint
      tags: []
      responses: {}
      operationId: post-users-userId
      x-stoplight:
        id: biijxcyrtsatx
    put:
      summary: Your PUT endpoint
      tags: []
      responses: {}
      operationId: put-users-userId
      x-stoplight:
        id: jotbt3tdyejme
  /user:
    post:
      summary: Create New User
      operationId: post-user
      responses:
        '200':
          description: User Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                New User Bob Fellow:
                  value:
                    id: 12
                    firstName: Bob
                    lastName: Fellow
                    email: bob.fellow@gmail.com
                    dateOfBirth: '1996-08-24'
                    emailVerified: false
                    createDate: '2020-11-18'
        '400':
          description: Missing Required Information
        '409':
          description: Email Already Taken
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                dateOfBirth:
                  type: string
                  format: date
              required:
                - firstName
                - lastName
                - email
                - dateOfBirth
            examples:
              Create User Bob Fellow:
                value:
                  firstName: Bob
                  lastName: Fellow
                  email: bob.fellow@gmail.com
                  dateOfBirth: '1996-08-24'
        description: Post the necessary fields for the API to create a new user.
      description: Create a new user.
      x-stoplight:
        id: thq2tump1oy0s
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
          x-stoplight:
            id: va5s6y2um7t5q
        firstName:
          type: string
          x-stoplight:
            id: 01ied95o4ighm
        lastName:
          type: string
          x-stoplight:
            id: xfmwjpye8dxq2
        email:
          type: string
          format: email
          x-stoplight:
            id: 9a8ogmqziwgwx
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
          x-stoplight:
            id: dk51yhrp8uek1
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
          x-stoplight:
            id: pv3fxknbwy2jr
        createDate:
          type: string
          format: date
          description: The date that the user was created.
          x-stoplight:
            id: deo1erevjdqh5
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
      x-stoplight:
        id: i0q872wogunaa
